<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: price.proto

namespace GPBMetadata;

class Price
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae8010a0b70726963652e70726f746f12057072696365223e0a0c50726963655265717565737412110a096d6f64656c436f6465180220012809120d0a05636f6c6f72180320012809120c0a047965617218042001280522310a0a50726963655265706c79120d0a05707269636518012001280512140a0c63757272656e6379436f6465180220012809323c0a0650726963657212320a08476574507269636512132e70726963652e5072696365526571756573741a112e70726963652e50726963655265706c794219aa02164175746f6261726e2e50726963696e67536572766572620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

