// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: price.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PriceRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PriceRoot : GPBRootObject
@end

#pragma mark - PriceRequest

typedef GPB_ENUM(PriceRequest_FieldNumber) {
  PriceRequest_FieldNumber_ModelCode = 2,
  PriceRequest_FieldNumber_Color = 3,
  PriceRequest_FieldNumber_Year = 4,
};

@interface PriceRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *modelCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *color;

@property(nonatomic, readwrite) int32_t year;

@end

#pragma mark - PriceReply

typedef GPB_ENUM(PriceReply_FieldNumber) {
  PriceReply_FieldNumber_Price = 1,
  PriceReply_FieldNumber_CurrencyCode = 2,
};

@interface PriceReply : GPBMessage

@property(nonatomic, readwrite) int32_t price;

@property(nonatomic, readwrite, copy, null_resettable) NSString *currencyCode;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
