<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: price.proto

namespace Price;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>price.PriceRequest</code>
 */
class PriceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string modelCode = 2;</code>
     */
    protected $modelCode = '';
    /**
     * Generated from protobuf field <code>string color = 3;</code>
     */
    protected $color = '';
    /**
     * Generated from protobuf field <code>int32 year = 4;</code>
     */
    protected $year = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $modelCode
     *     @type string $color
     *     @type int $year
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Price::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string modelCode = 2;</code>
     * @return string
     */
    public function getModelCode()
    {
        return $this->modelCode;
    }

    /**
     * Generated from protobuf field <code>string modelCode = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setModelCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->modelCode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string color = 3;</code>
     * @return string
     */
    public function getColor()
    {
        return $this->color;
    }

    /**
     * Generated from protobuf field <code>string color = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setColor($var)
    {
        GPBUtil::checkString($var, True);
        $this->color = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 year = 4;</code>
     * @return int
     */
    public function getYear()
    {
        return $this->year;
    }

    /**
     * Generated from protobuf field <code>int32 year = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setYear($var)
    {
        GPBUtil::checkInt32($var);
        $this->year = $var;

        return $this;
    }

}

