<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: price.proto

namespace Price;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>price.PriceReply</code>
 */
class PriceReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 price = 1;</code>
     */
    protected $price = 0;
    /**
     * Generated from protobuf field <code>string currencyCode = 2;</code>
     */
    protected $currencyCode = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $price
     *     @type string $currencyCode
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Price::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 price = 1;</code>
     * @return int
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>int32 price = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkInt32($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string currencyCode = 2;</code>
     * @return string
     */
    public function getCurrencyCode()
    {
        return $this->currencyCode;
    }

    /**
     * Generated from protobuf field <code>string currencyCode = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrencyCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->currencyCode = $var;

        return $this;
    }

}

